ALTER TABLE "productos_extra" ALTER COLUMN "id_producto" ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "productos_extra" ALTER COLUMN "estatus" SET NOT NULL;
ALTER TABLE "productos_extra" ALTER COLUMN "estatus" SET DEFAULT true;
ALTER TABLE "productos_extra" ALTER COLUMN "color" SET NOT NULL;
